### ISSUE TITLE
minified distro

### ISSUE THREAD

**Issue by Morriz** [dcohenb/angular-img-fallback#12]
Could you please not minify your scripts? Most of us do this in our projects build phase ourselves ;)

**Comment by dcohenb** [comment]
Feel free to use the unminified code.
Although you are not suppose to build external libs only concatenate them.

**Comment by Morriz** [comment]
I did. I copied it over your minified version. I don't understand what you mean by "not supposed to".  Not being able to step debug through your code is kind of a nono imo ;)

**Comment by dcohenb** [comment]
Will it help if the minified version will be inside a separated folder named "dist" like all the other libs are doing?

**Comment by Morriz** [comment]
No, it's nothing to do with that. How you build and concat/minify etc is your business. However, for the outside world you should list the unminified version in bower.json. So they can do it also however they wish ;)

**Comment by dcohenb** [comment]
Ok, I get what you mean. I replaced the main with the un-minified version.
thank you for your feedback!
