### ISSUE TITLE
Won't load a dynamic image

### ISSUE THREAD

**Issue by jamesvanleuven** [dcohenb/angular-img-fallback#16]
So I've noticed an interesting little bug...

<img data-ng-src="{{'path/to/image.jpg}}" fallback-src="{{'path/to/placeholder.png'}}" />
works fine

<img data-ng-src="path/to/{{'dynamic_content_id'}}" fallback-src="{{'path/to/fallback.png'}}" />

will not work at all, it renders the following error: "net::ERR_TOO_MANY_REDIRECTS"

so basically this is only a useful plug-in if we're dealing w/ static content - not if we're dealing with dynamic content....

**Comment by ckosloski** [comment]
I downloaded the source and changed two lines to fix this issue for me.

Line 25 changed to
`.directive('loadingSrc', ['$interpolate', function($interpolate) {`

Line 32 changed to
`img.src = $interpolate(attr.imgSrc)(scope);`
