### ISSUE TITLE
When the browser tries to re fetch the image for the second time, fallback-src dont work any more

### ISSUE THREAD

**Issue by siulung4073** [dcohenb/angular-img-fallback#18]
Hi, there.

I'm using md-autocomplete fro the material spec, and when you scroll and the item enter the visible part of the view, for some reason the browser tries to fetch the src image, and since the plugin unregisters from the error event, it no longer works

You'll see it in line 15: 

`element.off('error', errorHanlder);`

If you want to, I can try to make a pull request

thanks!

**Comment by dcohenb** [comment]
@siulung4073 First of all, yes. pull requests are welcome and appreciated.
Second, @david-meza PQ should have fixed the issue, can you please confirm?
