### ISSUE TITLE
Fallback image should replace loading image if regular image isn't found

### ISSUE THREAD

**Issue by david-meza** [dcohenb/angular-img-fallback#19]
Currently if you use both `fallback-src` and `loading-src` attributes, and the image inside `ng-src` is not found it doesn't replace the image with the fallback but stays on the loading image forever.

DEMO: https://plnkr.co/edit/2XSskxatdpVfHwvrdnnN?p=preview

**Comment by 700ghz** [comment]
Unfortunately, a similar problem
