### ISSUE TITLE
specifying loading-src  always loads fallback image !

### ISSUE THREAD

**Issue by uzumakinaruto123** [dcohenb/angular-img-fallback#21]
If i do this :- 

`<img ng-src="{{data.resimage}}" fallback-src="img/default{{ imageNo }}.jpg" alt="" />`

**Works great**

As soon as i add `loading-src` like dis :- 

``<img ng-src="{{data.resimage}}" loading-src fallback-src="img/default{{ imageNo }}.jpg" alt="" />``

IT WILL ALWAYS LOAD **FALLBACK**

I even tried this :- 

``<img ng-src="{{data.resimage}}" loading-src="img/default{{ imageNo }}.jpg" fallback-src="img/default{{ imageNo }}.jpg" alt="" />``

Help is appreciated ! Thanks.

**Comment by dcohenb** [comment]
i dont understand. if you provide the same source for fallback and loading what are you expecting?

**Comment by uzumakinaruto123** [comment]
No.i dont want to provide same src.  i just tried that second option ! so in the first one i added only loading-src .

I was expecting plugins default loading-src here. but got nothing different.

**Comment by uzumakinaruto123** [comment]
@dcohenb 

**UPDATE :-1** 

I removed fallback-src and used only loading-src , and it worked.

**Issue**

It works on within `ng-repeat` perfectly !

Problem occurs when using `collection-repeat` .
If collection repeat is used the img src is not updated and still shows fallback/loading src

**Comment by ssuhat** [comment]
+ 1 

I'm experiencing this. When I try load image from ajax request, the image always shown loading/fallback src. It never load the real image. But if I put the image directly (no ajax request),  the real image is load properly.

**Comment by dcohenb** [comment]
What's `collection-repeat`?
Can you provide a complete code sample of what is it that your trying to do?
"load image from ajax" just doesn't make much sense here

**Comment by uzumakinaruto123** [comment]
@dcohenb  ohh really sorry for that ! i forgot that its not a ionic framework.

well just to explain in short,

ionic framework in a hybrid app development framework in which apps are based on javascript.
ionic framework uses angular js wrapper  to do so.

ionic has an alternative to `ng-repeat` i.e `collection-repeat`

`collection-repeats` are used to improve the performance of list in angular or specifically ionic.


sorry for not mentioning that before.

**Comment by dcohenb** [comment]
@uzumakinaruto123 Thanks for the explanation, can you give me a code sample or a JSFiddle replicating the bug you're talking about? i really want to help you but i need to see the problem as i can't understand it from the description.

**Comment by uzumakinaruto123** [comment]
i tried my best to reproduce  ! i wonder if this is ionic issue ..

Here is the codepen

http://codepen.io/uzumakinaruto1/pen/wGPNbe

on this codepen if you check second list its `collection-repeat` which is `not loading ng-src image`
even if image is present.

ng-repeat loads it correctly. you can replace that 'collection' with 'ng' and you will see that it also works on second list. 

Thanks !
