### ISSUE TITLE
remove base-64 code

### ISSUE THREAD

**Issue by diegoarcega** [dcohenb/angular-img-fallback#24]
It is huge, make the loadingDefault and missingDefault configurable with a provider instead.

**with base-64**
angular.dcb-img-fallback.js (25,8kb)

**without base-64**
angular.dcb-img-fallback.js (1,8kb)

**Comment by dcohenb** [comment]
@diegoarcega You are defiantly right! this was done as a necessity when I first wrote the plugin.
but changing this now will defiantly not be backwards compatible.

what do you think, add another slim version `angular.dcb-img-fallback.slim.js` of the directive or redo it in a new non backwards compatible version?

**Comment by diegoarcega** [comment]
I believe the slim version is better, so we can choose which one to pick. 

One option is to swap that base64 for this 1px transparent "image":
`var missingDefault = "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";`

Definitively we should have that mate. 
Thanks for the great work there, the directive is just great :)

**Comment by dcohenb** [comment]
@diegoarcega I've released an update where the base64 is significantly minified.
It's should be a lot less noticeable now..
I'd appreciate your feedback
