### ISSUE TITLE
Update bower file

### ISSUE THREAD

**Issue by david-meza** [dcohenb/angular-img-fallback#25]
A couple months ago a PR I made was merged to the main branch. However, a new bower version was not released so users are still downloading an outdated version. Bumping up the version should fix issues like #23 and #21

**Comment by david-meza** [comment]
Currently, the only way to access the latest version is by adding this to bower:
```json
"dependencies": {
  "angular-img-fallback": "git://github.com/dcohenb/angular-img-fallback.git#ba4a6d9071814b6955aa049cb09dcb4c75955820"
},
```

**Comment by dcohenb** [comment]
Hi @david-meza Thank you for the help.
I've just deployed the updated version with a few improvements and your fix included.
I really appreciate your contribution.
