### ISSUE TITLE
Error when building with grunt-uglify

### ISSUE THREAD

**Issue by rotavio** [dcohenb/angular-img-fallback#27]
I'm using yeoman angular generator, and when I try to build my project I get the following error:

> > Uglifying source .tmp/concat/scripts/vendor.js failed.
> > Warning: Uglification failed.
> > SyntaxError: Unexpected token: operator (>).

This line refers to this one:
.directive('fallbackSrc', ['imageService', imageService => {

**Comment by dcohenb** [comment]
the code has been updated to ES6
you can use the minified version or add a preprocessor to your build (Babel
is a good choice)

**Comment by rotavio** [comment]
Thank you! I'll try that.
